[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index, follow"

[[redirects]]
  from = "/admin"
  to = "/admin/dashboard"
  status = 301

[[redirects]]
  from = "/client"
  to = "/client-portal"
  status = 301

[functions]
  node_bundler = "esbuild"